### ISSUE TITLE
hi can update?

### ISSUE THREAD

**Issue by AhrimanSefid** [Toomas633/Installers#1]
code:

https://raw.githubusercontent.com/AhrimanSefid/unminable/main/whalestonpool-gpu-ton-2.sh

https://raw.githubusercontent.com/AhrimanSefid/unminable/main/unminable-cpu.sh

**Comment by Toomas633** [comment]
The first one is for lolminer? (I have no experience with it as i have only used xmrig and nicehash)

The second one seems to be a simpler version for xmrig, which is already present, only differencd is that you use screen, mine configures it as a system service.

Am i correct?

**Comment by AhrimanSefid** [comment]
ok
but me need auto start background.
no kill.

**Comment by Toomas633** [comment]
System services start on boot and run on the backround, or you can disable the systemd service and start/stop it manually

**Comment by Toomas633** [comment]
I will take a look in the morning and send you back your scripts with edits for running as a service if you would like that?

**Comment by AhrimanSefid** [comment]
yes thanks share plz.

**Comment by Toomas633** [comment]
Here, they should work now as a service. If there are any issues then hit me up again.
PS: just to be safe run the scrips as a root user, or add sudo where needed in the scripts.

https://raw.githubusercontent.com/Toomas633/Installers/issues/updated_unminable-cpu.sh
https://raw.githubusercontent.com/Toomas633/Installers/issues/updated_whalestonpool-gpu-ton-2.sh

**Comment by AhrimanSefid** [comment]
./new-unminable-cpu.sh: line 11: /etc/systemd/system/xmrig.service: No such file or directory
./new-unminable-cpu.sh: line 25: systemctl: command not found

**Comment by Toomas633** [comment]
You are running them as root user on a debian distro like ubuntu, correct?

**Comment by AhrimanSefid** [comment]
1.50/logs/2022-01-05_20-03-41.log
1.50/mine_flux.sh
1.50/mine_bittube.sh
Created symlink /etc/systemd/system/multi-user.target.wants/lolMiner.service → /etc/systemd/system/lolMiner.service.

**Comment by AhrimanSefid** [comment]
can anydesk?

**Comment by Toomas633** [comment]
You are better of searching official forums for answers. I haven't used lolMiner before and thus don't know how to configure it. As far as i can see the scripts should work and xmrig install script that is provided in the repo works for me so.
